### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by msallin** [vanderkleij/Smocks#18]
Hi

I try to use Smock like this
```
Smock.Run(context =>
{
    context.Setup(() => DateTime.Now).Returns(DateTime.Now.AddDays(1));
    context.Setup(() => DateTime.UtcNow).Returns(DateTime.UtcNow.AddDays(1));
    Task<IList<TEntity>> myTask = Add();
    myTask.RunSynchronously();
});
```
Then I get a null reference:
```
Smocks.AppDomains.AppDomainContext.InvokeSerializableLambda[T](SerializableLambda`1 serializableFunc, Object target, Object[] arguments)
   at Smocks.AppDomains.AppDomainContext.Invoke[T](Action`1 action, T parameter)
   at Smocks.Smock.RunAction(Action`1 action, Configuration configuration)
   at Smocks.Smock.Run(Configuration configuration, Action`1 action)
   at Smocks.Smock.Run(Action`1 action)
```
Is this a bug or a limitation?

**Comment by vanderkleij** [comment]
Hi, thanks for reporting this. From the looks of it, `TEntity` is most likely a generic type parameter, and not an actual type. Can you confirm this? Can you expand the code example to a minimal, complete example that illustrates how/where TEntity is defined?

**Comment by msallin** [comment]
I'm calling a method which looks like that.
```
protected virtual async Task<IList<TEntity>> AddEntities(int amount, Action<TEntity> action)
{
    IList<TEntity> entityList = new List<TEntity>();
    for (int i = 0; i < amount; i++)
    {
        TEntity entity = CreateEntity();
        action(entity);
        var result = await Repository.InsertAsync(entity);
        result.EnsureIsValid();
        entityList.Add(entity);
    }

    return entityList;
}
```
Where the TEntity is 
RepositoryFixture<TEntity, TFilter, TRepository> : Fixture where TEntity : IEntity where TFilter : IFilter where TRepository : IRepository<TEntity, TFilter>

**Comment by vanderkleij** [comment]
This appears to be a bug. I will investigate and fix it in the near future. Thanks for reporting again!

**Comment by msallin** [comment]
Hi

To make it easier to reproduce I created a new project which contains the structure we use.
You can download it here: https://onedrive.live.com/redir?resid=C8E1BE3E79378699!631447&authkey=!AMlmgIqoGQ70pwI&ithint=file%2czip

Here I use Moq to abstract the repository. In the real tests there is a repository which abstracts the Entity Framework to access the database. I'm not sure if this is relevant for this bug.

However, I'm also not able to get this project run. There is another exception which is thrown. May this is depended to the this issue.

Please let me know when you need additional help.

Greetings

**Comment by ujeshmaurya** [comment]
Hello @vanderkleij 
This bug is resolved or not? As I am facing the same issue of NullReferenceException while using Smocks. I tried to run the examples which you gave in the Readme file, they are giving the same exceptions.

**Comment by iwl** [comment]
> Hello @vanderkleij @ujeshmaurya This bug is resolved or not? As I am facing the same issue

I am also today, trying to smock DateTime.Now / Today
Probably the most common use case and seems to be a common problem below Enterprise version...
