### ISSUE TITLE
Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by davidbambridge** [vanderkleij/Smocks#21]
Hi,

So i was using smock without issue a few weeks ago, but going back to it now whenever I run my tests i'm getting the above error, full text below.

I'm running version 0.6.29 against .net framework 4.5.2

Any suggestions would be great.

thanks

Result StackTrace:	
Server stack trace: 
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
   at Smocks.IL.AssemblyRewriter.Rewrite(String path)
   at Smocks.AppDomains.AssemblyLoaderFactory.GetLoaderForAssembly(AssemblyName assemblyName)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Smocks.AppDomains.IAssemblyLoaderFactory.GetLoaderForAssembly(AssemblyName assemblyName)
   at Smocks.AppDomains.AssemblyResolver.LoadAssembly(AssemblyName assemblyName)
   at Smocks.AppDomains.AssemblyResolver.LoadAssembly(AssemblyName assemblyName)
   at Smocks.AppDomains.AssemblyResolver.LoadAssembly(AssemblyName assemblyName)
   at Smocks.AppDomains.AssemblyResolver.OnAssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)   at Smocks.AppDomains.AppDomainContext.InvokeLambda[T](SerializableLambda`1 serializableLambda, Object[] arguments)
   at Smocks.AppDomains.AppDomainContext.InvokeSerializableLambda[T](SerializableLambda`1 serializableFunc, Object target, Object[] arguments)
   at Smocks.AppDomains.AppDomainContext.Invoke[T](Action`1 action, T parameter)
   at Smocks.Smock.RunAction(Action`1 action, Configuration configuration)
   at Smocks.Smock.Run(Configuration configuration, Action`1 action)
   at Smocks.Smock.Run(Action`1 action)
Result Message:	
Test method XWS.Tests.StartupTests.ConfigureAuthTest threw exception: 
System.InvalidOperationException: Operation is not valid due to the current state of the object.

**Comment by vanderkleij** [comment]
Thanks for reporting. Do you have any clue what caused the code to stop working? Without any code that illustrates the problem, it'll be very hard to identify and resolve the problem. Could you try to reduce your code to a [minimal, complete example](http://stackoverflow.com/help/mcve) that exhibits the problem?

**Comment by davidbambridge** [comment]
Hi, sorry for the delay in reply.  It seems to have been caused by a .net update to 4.6.1.  I've worked around the problem by creating a new solution an rebuilding everything.  So you can ignore the issue if you want.

**Comment by dm-conti** [comment]
I have the same problem 
![image](https://user-images.githubusercontent.com/4570529/55876060-fed36680-5b96-11e9-858f-4d48362b293f.png)
I am trying with 4.6.1 and 4.5.2
GetStaticSession is a static methods that return a simple string.
