### ISSUE TITLE
Moq.Mock.Verify() using It.Is<T> inside Smock.Run throws MethodAccessException

### ISSUE THREAD

**Issue by bledbet** [vanderkleij/Smocks#26]
I'm not sure if this is a Moq problem or a Smocks problem, but this works:

```
public void AcceptsStoreList()
{
     Smock.Run(context =>
     {
          Setup(context);
                
          Target.Accept(DownloadedEvent);

          Mock.Get(WorksheetReaderFactory)
                    .Verify(m => m.EntityWorksheetReader(Worksheet, It.IsAny<CellArea>()), Times.Once);
     });
}
```

And this does not:

```
public void AcceptsStoreList()
{
     Smock.Run(context =>
     {
          Setup(context);
                
          Target.Accept(DownloadedEvent);

          Mock.Get(WorksheetReaderFactory)
                    .Verify(m => m.EntityWorksheetReader(Worksheet, It.Is<CellArea>(ca => ca.StartRow == 1 && ca.EndRow == 5 && ca.StartColumn == 0 && ca.EndColumn == 5)), Times.Once);
     });
}
```
The exception that is thrown is:

```
Error Message:
   Test method WorksheetExtractor.Test.Extractors.Walmart.V1.StoreListWorksheetExtractorTest.AcceptsStoreList threw exception:
System.MethodAccessException: Attempt by security transparent method '?  .(Aspose.Cells.WorksheetCollection)' to access security critical method 'Smocks.Setups.Interceptor.Intercept<Aspose.Cells.Worksheet>(System.Object[], System.Reflection.MethodBase)' failed.

Assembly 'Aspose.Cells, Version=8.8.1.0, Culture=neutral, PublicKeyToken=716fcc553a201e56' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.
Stack Trace:
    at ?  .(WorksheetCollection )
   at Aspose.Cells.WorksheetCollection.Add()
   at Aspose.Cells.WorksheetCollection.Add(String sheetName)
   at WorksheetExtractor.Test.Extractors.Walmart.V1.StoreListWorksheetExtractorTest.Setup(ISmocksContext smocksContext) in c:\Dev\Git\RetailData\import\WorksheetExtractor.Test\Extractors\Walmart\V1\StoreListWorksheetExtractorTest.cs:line 70
   at WorksheetExtractor.Test.Extractors.Walmart.V1.StoreListWorksheetExtractorTest.<AcceptsStoreList>b__2(ISmocksContext context) in c:\Dev\Git\RetailData\import\WorksheetExtractor.Test\Extractors\Walmart\V1\StoreListWorksheetExtractorTest.cs:line 130   at Smocks.AppDomains.AppDomainContext.InvokeSerializableLambda[T](SerializableLambda`1 serializableFunc, Object target, Object[] arguments)
   at Smocks.AppDomains.AppDomainContext.Invoke[T](Action`1 action, T parameter)
   at Smocks.Smock.RunAction(Action`1 action, Configuration configuration)
   at Smocks.Smock.Run(Configuration configuration, Action`1 action)
   at Smocks.Smock.Run(Action`1 action)
```
StoreListWorksheetExtractorTest.cs:line 70 refers to the "Workbook = new Workbook(new MemoryStream());" in the Setup method:

```
 public void Setup(ISmocksContext smocksContext)
        {
            SourceStream = Mock.Of<IStreamProxy>();

            //SourceStream = new StreamProxy(Assembly.GetExecutingAssembly().GetManifestResourceStream("WorksheetExtractor.Test.Extractors.Walmart.V1.StoreList.xls"));
            DestinationStream = Mock.Of<IStreamProxy>(); //(new StreamProxy(new MemoryStream()));

            Storage = Mock.Of<IDataFileStorage>();
            Mock.Get(Storage).Setup(m => m.OpenRead(DownloadedEvent.FileName)).Returns(SourceStream);
            Mock.Get(Storage).Setup(m => m.OpenWrite(It.IsAny<string>())).Returns(DestinationStream);


            Workbook = new Workbook(new MemoryStream());
            Worksheet = Workbook.Worksheets.Add("Wal-Mart Stores");
            Cell = Worksheet.Cells[1, 1];
            smocksContext.Setup(() => Workbook.Worksheets[It.IsAny<string>()]).Returns(Worksheet);
            smocksContext.Setup(() => Workbook.Worksheets["Wal-Mart Stores"]).Returns(Worksheet).Verifiable();
            smocksContext.Setup(() => Worksheet.Cells.MaxDisplayRange.FirstRow).Returns(0);
            smocksContext.Setup(() => Worksheet.Cells.MaxDisplayRange.RowCount).Returns(5);
            smocksContext.Setup(() => Worksheet.Cells.MaxDisplayRange.FirstColumn).Returns(0);
            smocksContext.Setup(() => Worksheet.Cells.MaxDisplayRange.ColumnCount).Returns(5);
            smocksContext.Setup(() => Worksheet.Cells.Find(It.IsAny<string>(), null, It.IsAny<FindOptions>())).Returns(Cell);
            smocksContext.Setup(() => Worksheet.Cells.Find("Store Nbr", null, It.IsAny<FindOptions>())).Returns(Cell).Verifiable();

            CellsFactory = Mock.Of<ICellsFactory>();
            Mock.Get(CellsFactory).Setup(m => m.Workbook(SourceStream)).Returns(Workbook);

            Reader = Mock.Of<IEntityCsvStreamReader<Store>>();
            WorksheetReaderFactory = Mock.Of<IEntityWorksheetReaderFactory<Store>>();
            Mock.Get(WorksheetReaderFactory)
                .Setup(m => m.EntityWorksheetReader(It.IsAny<Worksheet>(), It.IsAny<CellArea>()))
                .Returns(Reader);

            Writer = Mock.Of<IEntityCsvStreamWriter<Store>>();
            CsvWriterFactory = Mock.Of<IEntityCsvStreamWriterFactory<Store>>();
            Mock.Get(CsvWriterFactory).Setup(m => m.EntityCsvStreamWriter(DestinationStream.Stream)).Returns(Writer);

            Marshaller = Mock.Of<IMarshaller>();
            Producer = Mock.Of<IProducer>();

            Target = new StoreListWorksheetExtractor(Storage, CellsFactory, WorksheetReaderFactory, CsvWriterFactory,
                Marshaller, Producer);
        }
```
Workbook is a class from a third-party assembly, which doesn't implement any interfaces, and doesn't have virtual members, and is my reason for trying out smocks.  Is there anything that jumps out at you as something I might be doing wrong?

**Comment by vanderkleij** [comment]
Thanks for reporting this. The issue was that the third-party assembly (Aspose Cells) has the AllowPartiallyTrustedCallersAttribute attribute. Smocks rewrites the assembly to make calls to methods in the Smocks assembly, which is prevented by the .NET security model because of said attribute. I've added some code to strip assemblies from the AllowPartiallyTrustedCallersAttribute attribute when rewriting them, which should resolve this problem.

**Comment by vanderkleij** [comment]
The package for this fix is [available on nuget now](https://www.nuget.org/packages/Smocks/0.6.31).

**Comment by bledbet** [comment]
Looks like that did it - thanks!
